### ISSUE TITLE
Sidebar is not scrollable

### ISSUE THREAD

**Issue by WhosNickDoglio** [shahruz/order-of-x#2]
While testing #1 I noticed the sidebar gets cut off and can't be scrolled now that the series list is longer. 

I end up getting the following on the default view in Chrome, I can zoom out to make it fit but would be nice if you could scroll this.

<img width="296" alt="Screen Shot 2020-09-28 at 7 43 38 PM" src="https://user-images.githubusercontent.com/3968678/94496665-ff185500-01c2-11eb-8ed1-82616fa7ea36.png">

**Comment by shahruz** [comment]
Fixed in https://github.com/shahruz/order-of-x/commit/36e8296e234bf7cf2cea0d134a17c10719dd1c30. Thanks!
